foo = ['a', 'b', 'c']
print(foo[3])      # will this result in an error?

# Yes this will yield an OutOfRange error